export enum AustraliaAppellationEnum {
  ADELAIDE_HILLS = 'adelaide_hills',
  BAROSSA_VALLEY = 'barossa_valley',
  CLARE_VALLEY = 'clare_valley',
  COONAWARRA = 'coonawarra',
  EDEN_VALLEY = 'eden_valley',
  FRANKLAND_RIVER = 'frankland_river',
  GEOGRAPHE = 'geographe',
  GIPPSLAND = 'gippsland',
  GREAT_SOUTHERN = 'great_southern',
  HUNTER_VALLEY = 'hunter_valley',
  LANGHORNE_CREEK = 'langhorne_creek',
  MARGARET_RIVER = 'margaret_river',
  MC_LAREN_VALE = 'mc_laren_vale',
  MORNINGTON_PENINSULA = 'mornington_peninsula',
  PADTHAWAY = 'padthaway',
  PEMBERTON = 'pemberton',
  RIVERLAND = 'riverland',
  RUTHERGLEN = 'rutherglen',
  SOUTH_EASTERN_AUSTRALIA = 'south_eastern_australia',
  SWAN_DISTRICT = 'swan_district',
  TASMANIA = 'tasmania',
  YARRA_VALLEY = 'yarra_valley',
}
