export enum AustriaAppellationEnum {
  NIEDEROESTERREICH = 'niederosterreich',
  WEINVIERTEL = 'weinviertel',
  KREMSTAL = 'kremstal',
  KAMPTAL = 'kamptal',
  TRAISENTAL = 'traisental',
  WAGRAM = 'wagram',
  WACHAU = 'wachau',
  THERMENREGION = 'thermenregion',
  CARNUNTUM = 'carnuntum',
  LEITHABERG = 'leithaberg',
  MITTELBURGENLAND = 'mittelburgenland',
  NEUSIEDLERSEE = 'neusiedlersee',
  SUEDBURGENLAND = 'suedburgenland',
  SUDSTEIERMARK = 'suedsteiermark',
  VULKANLAND_STEIERMARK = 'vulkanland_steiermark',
}
