export enum FranceAppellationEnum {
  HAUT_MEDOC = 'haut_medoc',
  PAUILLAC = 'pauillac',
  MARGAUX = 'margaux',
  SAINT_JULIEN = 'saint_julien',
  SAINT_ESTEPHE = 'saint_estephe',
  SAINT_EMILION = 'saint_emilion',
  POMEROL = 'pomerol',
  GRAVES = 'graves',
  SAUTERNES = 'sauternes',
  CHABLIS = 'chablis',
  COTE_DE_NUITS = 'cote_de_nuits',
  COTE_DE_BEAUNE = 'cote_de_beaune',
  COTE_CHALONNAISE = 'cote_chalonnaise',
  MACONNAIS = 'maconnais',
  CHAMPAGNE = 'champagne',
  LOIRE = 'loire',
  RHONE = 'rhone',
  ALSACE = 'alsace',
  BEAUJOLAIS = 'beaujolais',
  LANGUEDOC_ROUSSILLON = 'languedoc_roussillon',
  PROVENCE = 'provence',
  SUD_OUEST = 'sud_ouest',
  JURA = 'jura',
  SAVOIE = 'savoie',
  CORSICA = 'corsica',
  FRANCHE_COMTE = 'franche_comte',
}
