export enum GermanyAppellationEnum {
  AHR = 'ahr',
  MOSEL = 'mosel',
  RHEINGAU = 'rheingau',
  PFALZ = 'pfalz',
  RHEINHESSEN = 'rheinhessen',
  BADEN = 'baden',
  WUERTTEMBERG = 'wuerttemberg',
  NAHE = 'nahe',
  MITTELRHEIN = 'mittelrhein',
  HESSISCHE_BERGSTRASSE = 'hessische_bergstrasse',
  FRANKEN = 'franken',
  SAALE_UNSTRUT = 'saale_unstrut',
  SACHSEN = 'sachsen',
}
