export const wineCardList = [
  {
    name: 'Cheateau Margaux',
    vintage: 2010,
    type: 'Red',
    totalStar: '5.0',
    version: '1.0.0',
  },
  {
    name: 'Domain Romanee Conti',
    vintage: 2011,
    type: 'Red',
    totalStar: '5.0',
    version: '1.0.0',
  },
  {
    name: 'Chateau Lafite Rothschild',
    vintage: 2013,
    type: 'Red',
    totalStar: '4.0',
    version: '1.0.0',
  },
  {
    name: 'Dom Perignon',
    vintage: 2013,
    type: 'Sparkling',
    totalStar: '4.5',
    version: '1.0.0',
  },
  {
    name: 'Bouchard Pere & Fils Meursault',
    vintage: 2017,
    type: 'White',
    totalStar: '3.5',
    version: '1.0.0',
  },
  {
    name: 'Chateau Margaux',
    vintage: 2010,
    type: 'Red',
    totalStar: '5.0',
    version: '1.0.0',
  },
  {
    name: 'Domain Romanee Conti',
    vintage: 2011,
    type: 'Red',
    totalStar: '5.0',
    version: '1.0.0',
  },
  {
    name: 'Pierre Girardin Pommard Les Noizons',
    vintage: 2019,
    type: 'Red',
    totalStar: '4.5',
    version: '1.0.0',
  },
  {
    name: 'Chateau Latour',
    vintage: 2015,
    type: 'Red',
    totalStar: '4.5',
    version: '1.0.0',
  },
  {
    name: 'Domain Romanee Conti',
    vintage: 2011,
    type: 'Red',
    totalStar: '5.0',
    version: '1.0.0',
  },
];

export const whiskeyCardList = [
  {
    name: 'Macallan 18y',
    type: 'Whiskey',
    totalStar: '5.0',
    version: '1.0.0',
  },
  {
    name: 'Lagavulin 16y',
    type: 'Whiskey',
    totalStar: '5.0',
    version: '1.0.0',
  },
  {
    name: 'Glenfiddich 12y',
    type: 'Whiskey',
    totalStar: '3.0',
    version: '1.0.0',
  },
  {
    name: 'Jack Daniel',
    type: 'Whiskey',
    totalStar: '4.5',
    version: '1.0.0',
  },
  {
    name: 'Jameson',
    type: 'Whiskey',
    totalStar: '3.5',
    version: '1.0.0',
  },
  {
    name: 'Macallan 12y',
    type: 'Whiskey',
    totalStar: '4.0',
    version: '1.0.0',
  },
  {
    name: 'Lagavulin 8y',
    type: 'Whiskey',
    totalStar: '5.0',
    version: '1.0.0',
  },
  {
    name: 'Glenfiddich 18y',
    type: 'Whiskey',
    totalStar: '3.5',
    version: '1.0.0',
  },
  {
    name: 'Jack Daniel',
    type: 'Whiskey',
    totalStar: '4.5',
    version: '1.0.0',
  },
  {
    name: 'Jameson',
    type: 'Whiskey',
    totalStar: '3.5',
    version: '1.0.0',
  },
];

export const cocktailCardList = [
  {
    name: 'Margarita',
    type: 'Cocktail',
    totalStar: '5.0',
    version: '1.0.0',
  },
  {
    name: 'Martini',
    type: 'Cocktail',
    totalStar: '5.0',
    version: '1.0.0',
  },
  {
    name: 'Mojito',
    type: 'Cocktail',
    totalStar: '4.0',
    version: '1.0.0',
  },
  {
    name: 'Old Fashioned',
    type: 'Cocktail',
    totalStar: '4.5',
    version: '1.0.0',
  },
  {
    name: 'Cosmopolitan',
    type: 'Cocktail',
    totalStar: '3.5',
    version: '1.0.0',
  },
  {
    name: 'Margarita',
    type: 'Cocktail',
    totalStar: '5.0',
    version: '1.0.0',
  },
  {
    name: 'Martini',
    type: 'Cocktail',
    totalStar: '5.0',
    version: '1.0.0',
  },
  {
    name: 'Mojito',
    type: 'Cocktail',
    totalStar: '4.0',
    version: '1.0.0',
  },
  {
    name: 'Old Fashioned',
    type: 'Cocktail',
    totalStar: '4.5',
    version: '1.0.0',
  },
  {
    name: 'Cosmopolitan',
    type: 'Cocktail',
    totalStar: '3.5',
    version: '1.0.0',
  },
];
