export const wineList = [
  {
    name: 'Wine 1',
    vintage: 2010,
    type: 'Red',
    totalStar: '5.0',
    version: '1.0.0',
  },
  {
    name: 'Wine 2',
    vintage: 2011,
    type: 'White',
    totalStar: '4.5',
    version: '1.0.0',
  },
  {
    name: 'Wine 3',
    vintage: 2012,
    type: 'Sparkling',
    totalStar: '4.0',
    version: '1.0.0',
  },
  {
    name: 'Wine 4',
    vintage: 2013,
    type: 'White',
    totalStar: '3.5',
    version: '1.0.0',
  },
  {
    name: 'Wine 5',
    vintage: 2014,
    type: 'Red',
    totalStar: '3.0',
    version: '1.0.0',
  },
  {
    name: 'Wine 6',
    vintage: 2015,
    type: 'White',
    totalStar: '2.5',
    version: '1.0.0',
  },
  {
    name: 'Wine 7',
    vintage: 2016,
    type: 'Red',
    totalStar: '2.0',
    version: '1.0.0',
  },
  {
    name: 'Wine 8',
    vintage: 2017,
    type: 'White',
    totalStar: '1.5',
    version: '1.0.0',
  },
  {
    name: 'Wine 9',
    vintage: 2018,
    type: 'Red',
    totalStar: '1.0',
    version: '1.0.0',
  },
  {
    name: 'Wine 10',
    vintage: 2019,
    type: 'White',
    totalStar: '0.5',
    version: '1.0.0',
  },
];
