export enum SpiritCategoryEnum {
  IRISH = 'irish',
  SCOTCH = 'scotch',
  BOURBON = 'bourbon',
  WHISKY = 'whisky',
  VODKA = 'vodka',
  GIN = 'gin',
  RUM = 'rum',
  TEQUILA = 'tequila',
  COGNAC = 'cognac',
  ARMAGNAC = 'armagnac',
  CALVADOS = 'calvados',
  BRANDY = 'brandy',
  LIQUEUR = 'liqueur',
  SOJU = 'soju',
  MAKGEOLLI = 'makgeolli',
  TRADITIONAL = 'traditional',
  OTHER = 'other',
}

export const SpiritCategoryOrder: SpiritCategoryEnum[] = [
  SpiritCategoryEnum.IRISH,
  SpiritCategoryEnum.SCOTCH,
  SpiritCategoryEnum.BOURBON,
  SpiritCategoryEnum.WHISKY,
  SpiritCategoryEnum.VODKA,
  SpiritCategoryEnum.GIN,
  SpiritCategoryEnum.RUM,
  SpiritCategoryEnum.TEQUILA,
  SpiritCategoryEnum.COGNAC,
  SpiritCategoryEnum.ARMAGNAC,
  SpiritCategoryEnum.CALVADOS,
  SpiritCategoryEnum.BRANDY,
  SpiritCategoryEnum.LIQUEUR,
  SpiritCategoryEnum.SOJU,
  SpiritCategoryEnum.MAKGEOLLI,
  SpiritCategoryEnum.TRADITIONAL,
  SpiritCategoryEnum.OTHER,
];
