export enum SpiritCategoryEnum {
  IRISH = 'irish',
  SCOTCH = 'scotch',
  BOURBON = 'bourbon',
  WHISKY = 'whisky',
  VODKA = 'vodka',
  GIN = 'gin',
  RUM = 'rum',
  TEQUILA = 'tequila',
  COGNAC = 'cognac',
  ARMAGNAC = 'armagnac',
  CALVADOS = 'calvados',
  BRANDY = 'brandy',
  LIQUEUR = 'liqueur',
  SOJU = 'soju',
  MAKGEOLLI = 'makgeolli',
  TRADITIONAL = 'traditional',
}
