export enum WineGrapeEnum {
  OTHER = 'other',
  ALBARINO = 'albarino',
  BARBERA = 'barbera',
  CABERNET_FRANC = 'cabernet_franc',
  CABERNET_SAUVIGNON = 'cabernet_sauvignon',
  CHARDONNAY = 'chardonnay',
  CHENIN_BLANC = 'chenin_blanc',
  GAMAY = 'gamay',
  GEWURZTRAMINER = 'gewurztraminer',
  GRENACHE = 'grenache',
  GRUNER_VELTLINER = 'gruner_veltliner',
  MALBEC = 'malbec',
  MERLOT = 'merlot',
  MOURVEDRE = 'mourvedre',
  MUSCAT = 'muscat',
  NEBBIOLO = 'nebbiolo',
  PETITE_SIRAH = 'petite_sirah',
  PINOT_BLANC = 'pinot_blanc',
  PINOT_GRIS = 'pinot_gris',
  PINOT_NOIR = 'pinot_noir',
  RIESLING = 'riesling',
  SAUVIGNON_BLANC = 'sauvignon_blanc',
  SANGIOVESE = 'sangiovese',
  SEMILLON = 'semillon',
  SYRAH = 'syrah',
  TEMPRANILLO = 'tempranillo',
  VIOGNIER = 'viognier',
  ZINFANDEL = 'zinfandel',
}

export const WineGrapeOrder: WineGrapeEnum[] = [
  WineGrapeEnum.OTHER,
  WineGrapeEnum.ALBARINO,
  WineGrapeEnum.BARBERA,
  WineGrapeEnum.CABERNET_FRANC,
  WineGrapeEnum.CABERNET_SAUVIGNON,
  WineGrapeEnum.CHARDONNAY,
  WineGrapeEnum.CHENIN_BLANC,
  WineGrapeEnum.GAMAY,
  WineGrapeEnum.GEWURZTRAMINER,
  WineGrapeEnum.GRENACHE,
  WineGrapeEnum.GRUNER_VELTLINER,
  WineGrapeEnum.MALBEC,
  WineGrapeEnum.MERLOT,
  WineGrapeEnum.MOURVEDRE,
  WineGrapeEnum.MUSCAT,
  WineGrapeEnum.NEBBIOLO,
  WineGrapeEnum.PETITE_SIRAH,
  WineGrapeEnum.PINOT_BLANC,
  WineGrapeEnum.PINOT_GRIS,
  WineGrapeEnum.PINOT_NOIR,
  WineGrapeEnum.RIESLING,
  WineGrapeEnum.SAUVIGNON_BLANC,
  WineGrapeEnum.SANGIOVESE,
  WineGrapeEnum.SEMILLON,
  WineGrapeEnum.SYRAH,
  WineGrapeEnum.TEMPRANILLO,
  WineGrapeEnum.VIOGNIER,
  WineGrapeEnum.ZINFANDEL,
];
