export enum WineRegionEnum {
  OTHER = 'other',
  ARGENTINA = 'argentina',
  AUSTRALIA = 'australia',
  AUSTRIA = 'austria',
  CANADA = 'canada',
  CHILE = 'chile',
  FRANCE = 'france',
  GERMANY = 'germany',
  GREECE = 'greece',
  ITALY = 'italy',
  NEW_ZEALAND = 'new_zealand',
  PORTUGAL = 'portugal',
  SOUTH_AFRICA = 'south_africa',
  SPAIN = 'spain',
  USA = 'usa',
}

export const WineRegionOrder: WineRegionEnum[] = [
  WineRegionEnum.OTHER,
  WineRegionEnum.ARGENTINA,
  WineRegionEnum.AUSTRALIA,
  WineRegionEnum.AUSTRIA,
  WineRegionEnum.CANADA,
  WineRegionEnum.CHILE,
  WineRegionEnum.FRANCE,
  WineRegionEnum.GERMANY,
  WineRegionEnum.GREECE,
  WineRegionEnum.ITALY,
  WineRegionEnum.NEW_ZEALAND,
  WineRegionEnum.PORTUGAL,
  WineRegionEnum.SOUTH_AFRICA,
  WineRegionEnum.SPAIN,
  WineRegionEnum.USA,
];
